export const testData = {
  agents: [
    {
      id: 1,
      name: "Sarah Mitchell",
      email: "sarah.mitchell@brokerpro.com",
      phone: "+1-555-0101",
      created_at: "2023-06-15T08:00:00Z",
    },
    {
      id: 2,
      name: "James Thornton",
      email: "james.thornton@brokerpro.com",
      phone: "+1-555-0102",
      created_at: "2023-07-20T08:00:00Z",
    },
    {
      id: 3,
      name: "Priya Kapoor",
      email: "priya.kapoor@brokerpro.com",
      phone: "+1-555-0103",
      created_at: "2023-09-01T08:00:00Z",
    },
    {
      id: 4,
      name: "Marcus Webb",
      email: "marcus.webb@brokerpro.com",
      phone: "+1-555-0104",
      created_at: "2024-01-10T08:00:00Z",
    },
  ],
  properties: [
    {
      id: 1,
      agent_id: 1,
      title: "Spacious Family Home with Garden",
      description:
        "A beautifully maintained 4-bedroom home in the heart of Northside. Features an open-plan kitchen and living area, large covered deck, and a landscaped garden perfect for families. Double garage and ample storage.",
      price: 875000,
      beds: 4,
      baths: 2,
      property_type: "house",
      suburb: "Northside",
      address: "14 Elm Street, Northside",
      status: "active",
      internal_notes:
        "Vendor motivated to sell within 60 days. Open to offers above $850k.",
      created_at: "2024-10-01T09:00:00Z",
    },
    {
      id: 2,
      agent_id: 1,
      title: "Modern City Apartment with Skyline Views",
      description:
        "Sleek 2-bedroom apartment on the 18th floor with floor-to-ceiling windows and stunning city views. Fully renovated kitchen, in-building gym and rooftop terrace. Ideal for professionals.",
      price: 620000,
      beds: 2,
      baths: 2,
      property_type: "apartment",
      suburb: "Midtown",
      address: "18/302 Harbour Boulevard, Midtown",
      status: "active",
      internal_notes:
        "Building has an unresolved strata dispute. Flag to admin before showing.",
      created_at: "2024-10-05T10:00:00Z",
    },
    {
      id: 3,
      agent_id: 2,
      title: "Charming Cottage Near the River",
      description:
        "A quaint 3-bedroom cottage with original hardwood floors and a wrap-around porch. Walking distance to riverside parks and local cafés. Recently updated bathroom and kitchen.",
      price: 540000,
      beds: 3,
      baths: 1,
      property_type: "house",
      suburb: "Riverside",
      address: "7 Willow Lane, Riverside",
      status: "active",
      internal_notes:
        "Roof inspection pending. Estimated repair cost $8,000–$12,000.",
      created_at: "2024-10-08T11:00:00Z",
    },
    {
      id: 4,
      agent_id: 2,
      title: "Brand New Townhouse — Corner Position",
      description:
        "Freshly built 3-bedroom townhouse in a boutique development of 6. Corner position with extra windows and natural light. Stone benchtops, ducted air, single lock-up garage. Low maintenance living.",
      price: 730000,
      beds: 3,
      baths: 2,
      property_type: "townhouse",
      suburb: "Eastfield",
      address: "1/55 Boundary Road, Eastfield",
      status: "active",
      internal_notes:
        "Developer offering $5,000 in fixtures credit to close before end of financial year.",
      created_at: "2024-10-10T09:30:00Z",
    },
    {
      id: 5,
      agent_id: 3,
      title: "Executive Home on Large Block",
      description:
        "Stunning 5-bedroom home on 900sqm in a prestigious quiet street. Theatre room, home office, wine cellar, and resort-style pool. Triple garage. A rare executive offering.",
      price: 1450000,
      beds: 5,
      baths: 3,
      property_type: "house",
      suburb: "Northside",
      address: "3 Prestige Drive, Northside",
      status: "active",
      internal_notes:
        "Vendor has already purchased elsewhere. Genuine deadline — auction brought forward to Nov 2.",
      created_at: "2024-10-12T14:00:00Z",
    },
    {
      id: 6,
      agent_id: 3,
      title: "Affordable Studio in the CBD",
      description:
        "Compact and cleverly designed studio apartment on the 5th floor of a well-managed building. Built-in wardrobe, updated bathroom, access to shared laundry. Ideal first home or investment.",
      price: 285000,
      beds: 1,
      baths: 1,
      property_type: "apartment",
      suburb: "CBD",
      address: "5/88 King Street, CBD",
      status: "active",
      internal_notes:
        "Tenant in place until March. Yield approx 5.2%. Good investment buy.",
      created_at: "2024-10-15T08:45:00Z",
    },
    {
      id: 7,
      agent_id: 4,
      title: "Renovated Bungalow with Pool",
      description:
        "Fully renovated 3-bedroom bungalow featuring a heated pool, outdoor entertaining area, and brand new kitchen with island bench. All the hard work is done — just move in.",
      price: 695000,
      beds: 3,
      baths: 2,
      property_type: "house",
      suburb: "Westgrove",
      address: "22 Sunset Avenue, Westgrove",
      status: "active",
      internal_notes:
        "Multiple offers expected. Vendor will review all offers on Saturday at 5pm.",
      created_at: "2024-10-18T10:15:00Z",
    },
    {
      id: 8,
      agent_id: 4,
      title: "Luxury Penthouse — Panoramic Views",
      description:
        "An exceptional top-floor penthouse with 270-degree views of the city and bay. 3 bedrooms, 2 bathrooms, a gourmet kitchen, private rooftop terrace, 2 car spaces. The pinnacle of urban living.",
      price: 2100000,
      beds: 3,
      baths: 2,
      property_type: "apartment",
      suburb: "Midtown",
      address: "PH1/1 Sky Tower, Midtown",
      status: "active",
      internal_notes:
        "Foreign buyer inquiry flagged — compliance check required before proceeding.",
      created_at: "2024-10-20T13:00:00Z",
    },
    {
      id: 9,
      agent_id: 1,
      title: "Investor Special — Dual Income Property",
      description:
        "Rare dual-occupancy property generating strong rental returns. Main house is 3 beds, 1 bath; rear unit is 1 bed, 1 bath. Separate entrances and power meters. R3 zoning.",
      price: 920000,
      beds: 4,
      baths: 2,
      property_type: "house",
      suburb: "Eastfield",
      address: "101 Commerce Street, Eastfield",
      status: "under_contract",
      internal_notes:
        "Under contract — finance clause expires Nov 8. Keep as backup for interested buyers.",
      created_at: "2024-09-25T09:00:00Z",
    },
    {
      id: 10,
      agent_id: 2,
      title: "Stylish 2-Bed Townhouse Near Schools",
      description:
        "Low-maintenance 2-bedroom townhouse in a quiet complex of 10. Open-plan living, private courtyard, single garage. Minutes walk to primary school, parks, and public transport.",
      price: 490000,
      beds: 2,
      baths: 1,
      property_type: "townhouse",
      suburb: "Riverside",
      address: "4/18 Ferndale Close, Riverside",
      status: "active",
      internal_notes:
        "Owner-occupier moving interstate. Flexible settlement preferred.",
      created_at: "2024-10-22T08:00:00Z",
    },
    {
      id: 11,
      agent_id: 3,
      title: "Heritage Home — Fully Restored",
      description:
        "A meticulously restored 4-bedroom heritage home retaining original cornices, fireplaces, and Baltic pine floors while integrating modern comforts. Rear extension adds a contemporary open-plan living space.",
      price: 1180000,
      beds: 4,
      baths: 2,
      property_type: "house",
      suburb: "Northside",
      address: "9 Heritage Row, Northside",
      status: "active",
      internal_notes:
        "Heritage overlay applies. Any external modifications require council approval.",
      created_at: "2024-10-24T11:30:00Z",
    },
    {
      id: 12,
      agent_id: 4,
      title: "Ground Floor Unit with Courtyard",
      description:
        "Spacious ground floor 2-bedroom unit with direct access to a private courtyard. Freshly painted, new carpet, updated kitchen. Pet-friendly complex. Walk to shops and cafés.",
      price: 395000,
      beds: 2,
      baths: 1,
      property_type: "apartment",
      suburb: "Westgrove",
      address: "1/45 Garden Terrace, Westgrove",
      status: "active",
      internal_notes:
        "Strata levies $980/quarter. No known special levies pending.",
      created_at: "2024-10-26T09:00:00Z",
    },
    {
      id: 13,
      agent_id: 1,
      title: "First Home Buyer Opportunity",
      description:
        "Neat and tidy 2-bedroom home on a 450sqm block. Perfect for a first home buyer or downsizer. Single carport, established garden, close to public transport and local schools.",
      price: 435000,
      beds: 2,
      baths: 1,
      property_type: "house",
      suburb: "CBD",
      address: "32 Linden Street, CBD",
      status: "active",
      internal_notes:
        "Priced to sell quickly. Vendor has accepted a job offer interstate.",
      created_at: "2024-10-28T10:00:00Z",
    },
    {
      id: 14,
      agent_id: 2,
      title: "Highrise 1-Bed with Balcony",
      description:
        "Bright 1-bedroom apartment on level 12 with east-facing balcony and morning light. Secure building, intercom, lift access, on-site management. Close to university and hospital precinct.",
      price: 310000,
      beds: 1,
      baths: 1,
      property_type: "apartment",
      suburb: "Midtown",
      address: "12/77 University Road, Midtown",
      status: "active",
      internal_notes:
        "Short-term rental history. FIRB approval may be needed for certain buyers.",
      created_at: "2024-10-29T08:30:00Z",
    },
    {
      id: 15,
      agent_id: 3,
      title: "Large Family Home — Pool & Granny Flat",
      description:
        "Impressive 5-bedroom home with a self-contained granny flat, inground pool, and a triple garage. Perfect for multi-generational living or extra rental income. Short walk to shops and schools.",
      price: 1350000,
      beds: 5,
      baths: 3,
      property_type: "house",
      suburb: "Westgrove",
      address: "88 Panorama Drive, Westgrove",
      status: "active",
      internal_notes:
        "Granny flat not council approved. Vendor aware. Buyer to do own due diligence.",
      created_at: "2024-10-30T12:00:00Z",
    },
  ],
};
